alder -p alder_Palestine_EGYPT.par > alder_Palestine_EGYPT.log
alder -p alder_Palestine_Iran.par > alder_Palestine_Iran.log
alder -p alder_Palestine_SOMALI.par > alder_Palestine_SOMALI.log
alder -p alder_Palestine_OROMO.par > alder_Palestine_OROMO.log
alder -p alder_Palestine_AMHARA.par > alder_Palestine_AMHARA.log
alder -p alder_Palestine_WOLAYTA.par > alder_Palestine_WOLAYTA.log
alder -p alder_Palestine_GUMUZ.par > alder_Palestine_GUMUZ.log
alder -p alder_Palestine_Jordan.par > alder_Palestine_Jordan.log
alder -p alder_Palestine_Syria.par > alder_Palestine_Syria.log
alder -p alder_Palestine_Egyptian.par > alder_Palestine_Egyptian.log
alder -p alder_Palestine_French.par > alder_Palestine_French.log
alder -p alder_Palestine_Yoruba.par > alder_Palestine_Yoruba.log
alder -p alder_EGYPT_Iran.par > alder_EGYPT_Iran.log
alder -p alder_EGYPT_SOMALI.par > alder_EGYPT_SOMALI.log
alder -p alder_EGYPT_OROMO.par > alder_EGYPT_OROMO.log
alder -p alder_EGYPT_AMHARA.par > alder_EGYPT_AMHARA.log
alder -p alder_EGYPT_WOLAYTA.par > alder_EGYPT_WOLAYTA.log
alder -p alder_EGYPT_GUMUZ.par > alder_EGYPT_GUMUZ.log
alder -p alder_EGYPT_Jordan.par > alder_EGYPT_Jordan.log
alder -p alder_EGYPT_Syria.par > alder_EGYPT_Syria.log
alder -p alder_EGYPT_Egyptian.par > alder_EGYPT_Egyptian.log
alder -p alder_EGYPT_French.par > alder_EGYPT_French.log
alder -p alder_EGYPT_Yoruba.par > alder_EGYPT_Yoruba.log
alder -p alder_Iran_SOMALI.par > alder_Iran_SOMALI.log
alder -p alder_Iran_OROMO.par > alder_Iran_OROMO.log
alder -p alder_Iran_AMHARA.par > alder_Iran_AMHARA.log
alder -p alder_Iran_WOLAYTA.par > alder_Iran_WOLAYTA.log
alder -p alder_Iran_GUMUZ.par > alder_Iran_GUMUZ.log
alder -p alder_Iran_Jordan.par > alder_Iran_Jordan.log
alder -p alder_Iran_Syria.par > alder_Iran_Syria.log
alder -p alder_Iran_Egyptian.par > alder_Iran_Egyptian.log
alder -p alder_Iran_French.par > alder_Iran_French.log
alder -p alder_Iran_Yoruba.par > alder_Iran_Yoruba.log
alder -p alder_SOMALI_OROMO.par > alder_SOMALI_OROMO.log
alder -p alder_SOMALI_AMHARA.par > alder_SOMALI_AMHARA.log
alder -p alder_SOMALI_WOLAYTA.par > alder_SOMALI_WOLAYTA.log
alder -p alder_SOMALI_GUMUZ.par > alder_SOMALI_GUMUZ.log
alder -p alder_SOMALI_Jordan.par > alder_SOMALI_Jordan.log
alder -p alder_SOMALI_Syria.par > alder_SOMALI_Syria.log
alder -p alder_SOMALI_Egyptian.par > alder_SOMALI_Egyptian.log
alder -p alder_SOMALI_French.par > alder_SOMALI_French.log
alder -p alder_SOMALI_Yoruba.par > alder_SOMALI_Yoruba.log
alder -p alder_OROMO_AMHARA.par > alder_OROMO_AMHARA.log
alder -p alder_OROMO_WOLAYTA.par > alder_OROMO_WOLAYTA.log
alder -p alder_OROMO_GUMUZ.par > alder_OROMO_GUMUZ.log
alder -p alder_OROMO_Jordan.par > alder_OROMO_Jordan.log
alder -p alder_OROMO_Syria.par > alder_OROMO_Syria.log
alder -p alder_OROMO_Egyptian.par > alder_OROMO_Egyptian.log
alder -p alder_OROMO_French.par > alder_OROMO_French.log
alder -p alder_OROMO_Yoruba.par > alder_OROMO_Yoruba.log
alder -p alder_AMHARA_WOLAYTA.par > alder_AMHARA_WOLAYTA.log
alder -p alder_AMHARA_GUMUZ.par > alder_AMHARA_GUMUZ.log
alder -p alder_AMHARA_Jordan.par > alder_AMHARA_Jordan.log
alder -p alder_AMHARA_Syria.par > alder_AMHARA_Syria.log
alder -p alder_AMHARA_Egyptian.par > alder_AMHARA_Egyptian.log
alder -p alder_AMHARA_French.par > alder_AMHARA_French.log
alder -p alder_AMHARA_Yoruba.par > alder_AMHARA_Yoruba.log
alder -p alder_WOLAYTA_GUMUZ.par > alder_WOLAYTA_GUMUZ.log
alder -p alder_WOLAYTA_Jordan.par > alder_WOLAYTA_Jordan.log
alder -p alder_WOLAYTA_Syria.par > alder_WOLAYTA_Syria.log
alder -p alder_WOLAYTA_Egyptian.par > alder_WOLAYTA_Egyptian.log
alder -p alder_WOLAYTA_French.par > alder_WOLAYTA_French.log
alder -p alder_WOLAYTA_Yoruba.par > alder_WOLAYTA_Yoruba.log
alder -p alder_GUMUZ_Jordan.par > alder_GUMUZ_Jordan.log
alder -p alder_GUMUZ_Syria.par > alder_GUMUZ_Syria.log
alder -p alder_GUMUZ_Egyptian.par > alder_GUMUZ_Egyptian.log
alder -p alder_GUMUZ_French.par > alder_GUMUZ_French.log
alder -p alder_GUMUZ_Yoruba.par > alder_GUMUZ_Yoruba.log
alder -p alder_Jordan_Syria.par > alder_Jordan_Syria.log
alder -p alder_Jordan_Egyptian.par > alder_Jordan_Egyptian.log
alder -p alder_Jordan_French.par > alder_Jordan_French.log
alder -p alder_Jordan_Yoruba.par > alder_Jordan_Yoruba.log
alder -p alder_Syria_Egyptian.par > alder_Syria_Egyptian.log
alder -p alder_Syria_French.par > alder_Syria_French.log
alder -p alder_Syria_Yoruba.par > alder_Syria_Yoruba.log
alder -p alder_Egyptian_French.par > alder_Egyptian_French.log
alder -p alder_Egyptian_Yoruba.par > alder_Egyptian_Yoruba.log
alder -p alder_French_Yoruba.par > alder_French_Yoruba.log
