colors = {'Sad': 'yellow',
     'Amr': 'yellow',
     'San': 'yellow',
     'Dhm': 'yellow',
     
     'Mhw': 'orange', 
     'Haj': 'orange',

     'Hdr': 'green',
     'Shb': 'green',
     
     'Ibb': 'purple',
     'Tiz': 'purple',
     
     'Jwf': 'blue',
     'Mrb': 'blue',
     'Byd': 'blue',
     
     'Dal': 'red',
     'Lahj': 'red',
     'Abyn': 'red',

     'Rsa': 'black',
     'HGDP': "lightgrey"
    }



colors2 = {'Malawi': 'red',
         'Russia': 'magenta',
         'Azerbaijan': 'orchid',
         'Armenia': 'violet',
         'Moldova': 'olive',
         'Turkey': 'pink',
         'Georgia': 'plum',
         'Uzbekistan': 'mediumorchid',
         'Kazakhstan': 'darkorchid',
         'Mongolia': 'purple',
         'Tajikistan': 'darkviolet',
         'Ukraine': 'orange',
         'South Africa': 'firebrick',
         'Pakistan': 'magenta',
         'Congo': 'tomato',
         'Central African Republic': 'indianred',
         'Papua New Guinea': 'green',
         'France': 'yellow',
         'Israel': 'darkturquoise',
         'Italy': 'gold',
         'Colombia': 'indigo',
         'Cambodia': 'mediumslateblue',
         'Japan': 'purple',
         'China': 'mediumvioletred',
         'Great Britain': 'yellowgreen',
         'Brazil': 'thistle',
         'Mexico': 'blueviolet',
         'Senegal': 'orangered',
         'Nigeria': 'salmon',
         'Namibia': 'darksalmon',
         'Lesotho': 'lightcoral',
         'Botswana': 'chocolate',
         'Angola': 'coral',
         'Algeria': 'blue',
         'Kenya': 'crimson',
         '..': 'whitesmoke',
         'Croatia': 'khaki',
         'Australia': 'teal',
         'Tanzania': 'lightcoral',
         'USA': 'lemonchiffon',
         'Finland': 'lightyellow',
         'Ethiopia': 'darkred',
         'Morocco': 'dodgerblue',
         'Sudan': 'maroon',
         'Greece': 'bisque',
         'Bulgaria': 'antiquewhite',
         'Hungary': 'cornsilk',
         'Lithuania': 'linen',
         'Iran': 'palevioletred',
         'Syria': 'teal',
         'Lebanon': 'cadetblue',
         'Saudi Arabia': 'cyan',
         'Jordan': 'paleturquoise',
         'Yemen': 'springgreen',
         'Egypt': 'steelblue',
         'Abkhazia': 'plum',
         'Belarus': 'wheat',
         'Estonia': 'papayawhip',
         'Taiwan': 'mediumslateblue',
         'Czechoslovakia': 'khaki',
         'Iceland': 'navajowhite',
         'Peru': 'darkblue',
         'South Korea': 'mediumorchid',
         'Spain': 'burlywood',
         'Vietnam': 'palevioletred',
         'India': 'deeppink',
         'Bangladesh': 'hotpink',
         'Gambia': 'lightsalmon',
         'Sierra Leone': 'red',
         'Thailand': 'magenta',
         'Libya': 'royalblue',
         'Malta': 'darkkhaki',
         'Bolivia': 'darkslateblue',
         'Nepal': 'mediumorchid',
         'Tunisia': 'cornflowerblue',
         'Poland': 'lightgoldenrodyellow',
         'Norway': 'yellowgreen',
         'Albania': 'antiquewhite',
         'Iraq': 'violet',
         'Cyprus': 'bisque',
         'Kyrgyzstan': 'darkorchid',
         'Myanmar': 'orchid',
         'Brunei': 'mediumspringgreen',
         'Philippines': 'darkgreen',
         'Singapore': 'magenta',
         'Romania': 'palegoldenrod',
         'HumanReferenceSequence': 'gray',
         'Eritrea': 'rosybrown',
         'Vanuatu': 'limegreen',
         'Turkmenistan': 'darkorchid',
         'Czech Republic': 'khaki',
         'Portugal': 'yellow',
         'BotswanaOrNamibia': 'darksalmon',
         'Orkney Islands': 'blanchedalmond',
         'New Zealand': 'chartreuse',
         'Western Sahara (Morocco)': 'mediumblue',
         'Luxembourg': 'yellow',
         'Germany': 'yellow',
         'Canada': 'floralwhite',
         'Venezuela': 'darkslateblue',
         'Chile': 'darkslateblue',
         'Argentina': 'darkslateblue',
         'Belgium': 'yellow',
         'Tonga': 'sienna',
         'Sweden': 'moccasin',
         'Serbia': 'tan',
         'North Macedonia': 'bisque',
         'Greenland': 'yellow',
         'Denmark': 'yellow',
         'Montenegro': 'tan',
         'Austria': 'yellow',
         'Switzerland': 'yellow',
         'Ireland': 'yellow',
         'Netherlands': 'yellow',
         'Latvia': 'yellow',
         'Puerto Rico': 'darkslateblue',
         'Barbados': 'darkslateblue',
         'Sri Lanka': 'deeppink',
         'Afghanistan': 'darkviolet',
         'Belize': 'darkslateblue',
         'Canary Islands': 'yellow',
         'Solomon Islands': 'seagreen',
         'French Polynesia': 'mediumseagreen',
         'Dominican Republic': 'darkslateblue',
         'Gibraltar': 'yellow',
         'Bahamas': 'darkslateblue',
         'Slovakia': 'khaki',
         'Crimea': 'orange',
         'Curacao': 'darkslateblue',
         'Haiti': 'darkslateblue',
         'Indonesia': 'darkseagreen',
         'Malaysia': 'hotpink',
         'Laos': 'hotpink',
         'Cameroon': 'maroon',
         'China ': 'mediumvioletred',
         'DR Congo': 'red',
         'Uganda': 'red',
         'Cuba': 'darkslateblue',
         'Guadeloupe': 'darkslateblue',
         'St.Lucia': 'darkslateblue',
         'Azerbaijan ': 'orchid',
         'Turkey ': 'pink',
         'Isle of Man': 'yellow',
         'Faroes': 'yellow', 
                 'Sad': '#e4e8a5',
     'Amr': '#aaad70',
     'San': '#d3d6a7',
     'Dhm': '#7b7f41',
     
     'Mhw': '#e27612', 
     'Haj': '#edb077',

     'Hdr': 'green',
     'Shb': '#b3f03c',
     
     'Ibb': '#d3d3d2',
     'Tiz': '#96968d',
     
     'Jwf': '#65a5bb',
     'Mrb': '#3b52ad',
     'Byd': '#0f798c',
     
     'Dal': '#d88381',
     'Lahj': '#e7c6c2',
     'Abyn': '#b66056',

     'Rsa': 'black'}

markers = {'Sad': 'circle',
     'Amr': 'dot',
     'San': 'star',
     'Dhm': 'x',
     
     'Mhw': 'circle', 
     'Haj': 'x',

     'Hdr': 'circle',
     'Shb': 'x',
     
     'Ibb': 'circle',
     'Tiz': 'x',
     
     'Jwf': 'circle',
     'Mrb': 'x',
     'Byd': 'star',
     
     'Dal': 'circle',
     'Lahj': 'x',
     'Abyn': 'dot',

     'Rsa': 'circle'}


markers2 = {'Sad': 'circle',
     'Amr': 'cross',
     'San': 'diamond',
     'Dhm': 'x',
     
     'Mhw': 'circle', 
     'Haj': 'x',

     'Hdr': 'circle',
     'Shb': 'x',
     
     'Ibb': 'circle',
     'Tiz': 'x',
     
     'Jwf': 'circle',
     'Mrb': 'x',
     'Byd': 'diamond',
     
     'Dal': 'circle',
     'Lahj': 'x',
     'Abyn': 'cross',

     'Rsa': 'circle',
     'HGDP': 'plus',
     'Subsaharian_Africa': 'plus',
     'America': 'plus',
     'Asia': 'plus',
     'Europe': 'plus',
     'Middle_Est': 'plus',
     'North_Africa': 'plus',
     'Oceania': 'plus'         
    }

colorsHGDP = {      'Subsaharian_Africa': 'tomato',
     'America': 'purple',
     'Asia': 'hotpink',
     'Europe': 'goldenrod',
     'Middle_Est': 'aqua',
     'North_Africa': 'blue',
     'Oceania': 'darkolivegreen'         
}

emirates = 'abu_dhabi al_ain sharjah al_fujairah rak dubai uae'.split()
ecols = 'lightsalmon plum slateblue chartreuse springgreen darkorange darkgreen'.split()
colorsUAE = dict(zip(emirates, ecols))


colors.update(colorsHGDP)
colors.update(colorsUAE)
